version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: WwFFTRDJ7s2RgPWx
    volumes:
      - mydata:/var/lib/mysql
      - ./:/home/columbia/src/FintechDatabase
    ports:
      - 3306:3306
    networks:
      - fintech_local
networks:
    fintech_local:
volumes:
  mydata: